name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Panda Setup
      run: python3 -m pip install pandare
    - name: Build
      run: cd panda-rs && cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
